# Generated by Django 3.1.7 on 2021-02-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210225_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='done_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
