# Generated by Django 3.1.7 on 2021-02-25 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210225_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
