# Generated by Django 3.1.7 on 2021-02-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_due_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(choices=[('Success', 'success'), ('Danger', 'Danger'), ('Warning', 'Warning'), ('Info', 'Info'), ('Light', 'Light')], default='Light', max_length=7),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], default='Not Done', max_length=8),
        ),
    ]
